const USERS_LIST = [
  'bwowk',
  'xthiago',
  'degrecci',
  'victormiguez',
  'adrianuf22',
  'rvconessa',
  'mandyellow',
  'calderaricaio',
  'guiluchesi',
  'BrunohSL',
  'denidiasjr',
  'thayna-oliveira',
  'renan-ponciano',
  'romulojjunior',
  'CShigaki',
  'pethersonmoreno',
  'efeito',
  'magnusrusso',
  'rodrigoalexandrecosta',
  'sidelia',
  'cedric-matheus',
  'mario-balan',
  'eeleeoonee',
  'victorperin',
];

export default USERS_LIST;
